<?php

use Illuminate\Database\Seeder;

class KotasTableSeeder extends Seeder
{
  /**
  * Run the database seeds.
  *
  * @return void
  */
  public function run()
  {
    $Kota = [
      array('id' => '1101','provinsi_id' => '11','nama_kota' => 'KAB. ACEH SELATAN'),
      array('id' => '1102','provinsi_id' => '11','nama_kota' => 'KAB. ACEH TENGGARA'),
      array('id' => '1103','provinsi_id' => '11','nama_kota' => 'KAB. ACEH TIMUR'),
      array('id' => '1104','provinsi_id' => '11','nama_kota' => 'KAB. ACEH TENGAH'),
      array('id' => '1105','provinsi_id' => '11','nama_kota' => 'KAB. ACEH BARAT'),
      array('id' => '1106','provinsi_id' => '11','nama_kota' => 'KAB. ACEH BESAR'),
      array('id' => '1107','provinsi_id' => '11','nama_kota' => 'KAB. PIDIE'),
      array('id' => '1108','provinsi_id' => '11','nama_kota' => 'KAB. ACEH UTARA'),
      array('id' => '1109','provinsi_id' => '11','nama_kota' => 'KAB. SIMEULUE'),
      array('id' => '1110','provinsi_id' => '11','nama_kota' => 'KAB. ACEH SINGKIL'),
      array('id' => '1111','provinsi_id' => '11','nama_kota' => 'KAB. BIREUEN'),
      array('id' => '1112','provinsi_id' => '11','nama_kota' => 'KAB. ACEH BARAT DAYA'),
      array('id' => '1113','provinsi_id' => '11','nama_kota' => 'KAB. GAYO LUES'),
      array('id' => '1114','provinsi_id' => '11','nama_kota' => 'KAB. ACEH JAYA'),
      array('id' => '1115','provinsi_id' => '11','nama_kota' => 'KAB. NAGAN RAYA'),
      array('id' => '1116','provinsi_id' => '11','nama_kota' => 'KAB. ACEH TAMIANG'),
      array('id' => '1117','provinsi_id' => '11','nama_kota' => 'KAB. BENER MERIAH'),
      array('id' => '1118','provinsi_id' => '11','nama_kota' => 'KAB. PIDIE JAYA'),
      array('id' => '1171','provinsi_id' => '11','nama_kota' => 'KOTA BANDA ACEH'),
      array('id' => '1172','provinsi_id' => '11','nama_kota' => 'KOTA SABANG'),
      array('id' => '1173','provinsi_id' => '11','nama_kota' => 'KOTA LHOKSEUMAWE'),
      array('id' => '1174','provinsi_id' => '11','nama_kota' => 'KOTA LANGSA'),
      array('id' => '1175','provinsi_id' => '11','nama_kota' => 'KOTA SUBULUSSALAM'),
      array('id' => '1201','provinsi_id' => '12','nama_kota' => 'KAB. TAPANULI TENGAH'),
      array('id' => '1202','provinsi_id' => '12','nama_kota' => 'KAB. TAPANULI UTARA'),
      array('id' => '1203','provinsi_id' => '12','nama_kota' => 'KAB. TAPANULI SELATAN'),
      array('id' => '1204','provinsi_id' => '12','nama_kota' => 'KAB. NIAS'),
      array('id' => '1205','provinsi_id' => '12','nama_kota' => 'KAB. LANGKAT'),
      array('id' => '1206','provinsi_id' => '12','nama_kota' => 'KAB. KARO'),
      array('id' => '1207','provinsi_id' => '12','nama_kota' => 'KAB. DELI SERDANG'),
      array('id' => '1208','provinsi_id' => '12','nama_kota' => 'KAB. SIMALUNGUN'),
      array('id' => '1209','provinsi_id' => '12','nama_kota' => 'KAB. ASAHAN'),
      array('id' => '1210','provinsi_id' => '12','nama_kota' => 'KAB. LABUHANBATU'),
      array('id' => '1211','provinsi_id' => '12','nama_kota' => 'KAB. DAIRI'),
      array('id' => '1212','provinsi_id' => '12','nama_kota' => 'KAB. TOBA SAMOSIR'),
      array('id' => '1213','provinsi_id' => '12','nama_kota' => 'KAB. MANDAILING NATAL'),
      array('id' => '1214','provinsi_id' => '12','nama_kota' => 'KAB. NIAS SELATAN'),
      array('id' => '1215','provinsi_id' => '12','nama_kota' => 'KAB. PAKPAK BHARAT'),
      array('id' => '1216','provinsi_id' => '12','nama_kota' => 'KAB. HUMBANG HASUNDUTAN'),
      array('id' => '1217','provinsi_id' => '12','nama_kota' => 'KAB. SAMOSIR'),
      array('id' => '1218','provinsi_id' => '12','nama_kota' => 'KAB. SERDANG BEDAGAI'),
      array('id' => '1219','provinsi_id' => '12','nama_kota' => 'KAB. BATU BARA'),
      array('id' => '1220','provinsi_id' => '12','nama_kota' => 'KAB. PADANG LAWAS UTARA'),
      array('id' => '1221','provinsi_id' => '12','nama_kota' => 'KAB. PADANG LAWAS'),
      array('id' => '1222','provinsi_id' => '12','nama_kota' => 'KAB. LABUHANBATU SELATAN'),
      array('id' => '1223','provinsi_id' => '12','nama_kota' => 'KAB. LABUHANBATU UTARA'),
      array('id' => '1224','provinsi_id' => '12','nama_kota' => 'KAB. NIAS UTARA'),
      array('id' => '1225','provinsi_id' => '12','nama_kota' => 'KAB. NIAS BARAT'),
      array('id' => '1271','provinsi_id' => '12','nama_kota' => 'KOTA MEDAN'),
      array('id' => '1272','provinsi_id' => '12','nama_kota' => 'KOTA PEMATANG SIANTAR'),
      array('id' => '1273','provinsi_id' => '12','nama_kota' => 'KOTA SIBOLGA'),
      array('id' => '1274','provinsi_id' => '12','nama_kota' => 'KOTA TANJUNG BALAI'),
      array('id' => '1275','provinsi_id' => '12','nama_kota' => 'KOTA BINJAI'),
      array('id' => '1276','provinsi_id' => '12','nama_kota' => 'KOTA TEBING TINGGI'),
      array('id' => '1277','provinsi_id' => '12','nama_kota' => 'KOTA PADANGSIDIMPUAN'),
      array('id' => '1278','provinsi_id' => '12','nama_kota' => 'KOTA GUNUNGSITOLI'),
      array('id' => '1301','provinsi_id' => '13','nama_kota' => 'KAB. PESISIR SELATAN'),
      array('id' => '1302','provinsi_id' => '13','nama_kota' => 'KAB. SOLOK'),
      array('id' => '1303','provinsi_id' => '13','nama_kota' => 'KAB. SIJUNJUNG'),
      array('id' => '1304','provinsi_id' => '13','nama_kota' => 'KAB. TANAH DATAR'),
      array('id' => '1305','provinsi_id' => '13','nama_kota' => 'KAB. PADANG PARIAMAN'),
      array('id' => '1306','provinsi_id' => '13','nama_kota' => 'KAB. AGAM'),
      array('id' => '1307','provinsi_id' => '13','nama_kota' => 'KAB. LIMA PULUH KOTA'),
      array('id' => '1308','provinsi_id' => '13','nama_kota' => 'KAB. PASAMAN'),
      array('id' => '1309','provinsi_id' => '13','nama_kota' => 'KAB. KEPULAUAN MENTAWAI'),
      array('id' => '1310','provinsi_id' => '13','nama_kota' => 'KAB. DHARMASRAYA'),
      array('id' => '1311','provinsi_id' => '13','nama_kota' => 'KAB. SOLOK SELATAN'),
      array('id' => '1312','provinsi_id' => '13','nama_kota' => 'KAB. PASAMAN BARAT'),
      array('id' => '1371','provinsi_id' => '13','nama_kota' => 'KOTA PADANG'),
      array('id' => '1372','provinsi_id' => '13','nama_kota' => 'KOTA SOLOK'),
      array('id' => '1373','provinsi_id' => '13','nama_kota' => 'KOTA SAWAHLUNTO'),
      array('id' => '1374','provinsi_id' => '13','nama_kota' => 'KOTA PADANG PANJANG'),
      array('id' => '1375','provinsi_id' => '13','nama_kota' => 'KOTA BUKITTINGGI'),
      array('id' => '1376','provinsi_id' => '13','nama_kota' => 'KOTA PAYAKUMBUH'),
      array('id' => '1377','provinsi_id' => '13','nama_kota' => 'KOTA PARIAMAN'),
      array('id' => '1401','provinsi_id' => '14','nama_kota' => 'KAB. KAMPAR'),
      array('id' => '1402','provinsi_id' => '14','nama_kota' => 'KAB. INDRAGIRI HULU'),
      array('id' => '1403','provinsi_id' => '14','nama_kota' => 'KAB. BENGKALIS'),
      array('id' => '1404','provinsi_id' => '14','nama_kota' => 'KAB. INDRAGIRI HILIR'),
      array('id' => '1405','provinsi_id' => '14','nama_kota' => 'KAB. PELALAWAN'),
      array('id' => '1406','provinsi_id' => '14','nama_kota' => 'KAB. ROKAN HULU'),
      array('id' => '1407','provinsi_id' => '14','nama_kota' => 'KAB. ROKAN HILIR'),
      array('id' => '1408','provinsi_id' => '14','nama_kota' => 'KAB. SIAK'),
      array('id' => '1409','provinsi_id' => '14','nama_kota' => 'KAB. KUANTAN SINGINGI'),
      array('id' => '1410','provinsi_id' => '14','nama_kota' => 'KAB. KEPULAUAN MERANTI'),
      array('id' => '1471','provinsi_id' => '14','nama_kota' => 'KOTA PEKANBARU'),
      array('id' => '1472','provinsi_id' => '14','nama_kota' => 'KOTA DUMAI'),
      array('id' => '1501','provinsi_id' => '15','nama_kota' => 'KAB. KERINCI'),
      array('id' => '1502','provinsi_id' => '15','nama_kota' => 'KAB. MERANGIN'),
      array('id' => '1503','provinsi_id' => '15','nama_kota' => 'KAB. SAROLANGUN'),
      array('id' => '1504','provinsi_id' => '15','nama_kota' => 'KAB. BATANGHARI'),
      array('id' => '1505','provinsi_id' => '15','nama_kota' => 'KAB. MUARO JAMBI'),
      array('id' => '1506','provinsi_id' => '15','nama_kota' => 'KAB. TANJUNG JABUNG BARAT'),
      array('id' => '1507','provinsi_id' => '15','nama_kota' => 'KAB. TANJUNG JABUNG TIMUR'),
      array('id' => '1508','provinsi_id' => '15','nama_kota' => 'KAB. BUNGO'),
      array('id' => '1509','provinsi_id' => '15','nama_kota' => 'KAB. TEBO'),
      array('id' => '1571','provinsi_id' => '15','nama_kota' => 'KOTA JAMBI'),
      array('id' => '1572','provinsi_id' => '15','nama_kota' => 'KOTA SUNGAI PENUH'),
      array('id' => '1601','provinsi_id' => '16','nama_kota' => 'KAB. OGAN KOMERING ULU'),
      array('id' => '1602','provinsi_id' => '16','nama_kota' => 'KAB. OGAN KOMERING ILIR'),
      array('id' => '1603','provinsi_id' => '16','nama_kota' => 'KAB. MUARA ENIM'),
      array('id' => '1604','provinsi_id' => '16','nama_kota' => 'KAB. LAHAT'),
      array('id' => '1605','provinsi_id' => '16','nama_kota' => 'KAB. MUSI RAWAS'),
      array('id' => '1606','provinsi_id' => '16','nama_kota' => 'KAB. MUSI BANYUASIN'),
      array('id' => '1607','provinsi_id' => '16','nama_kota' => 'KAB. BANYUASIN'),
      array('id' => '1608','provinsi_id' => '16','nama_kota' => 'KAB. OGAN KOMERING ULU TIMUR'),
      array('id' => '1609','provinsi_id' => '16','nama_kota' => 'KAB. OGAN KOMERING ULU SELATAN'),
      array('id' => '1610','provinsi_id' => '16','nama_kota' => 'KAB. OGAN ILIR'),
      array('id' => '1611','provinsi_id' => '16','nama_kota' => 'KAB. EMPAT LAWANG'),
      array('id' => '1612','provinsi_id' => '16','nama_kota' => 'KAB. PENUKAL ABAB LEMATANG ILIR'),
      array('id' => '1613','provinsi_id' => '16','nama_kota' => 'KAB. MUSI RAWAS UTARA'),
      array('id' => '1671','provinsi_id' => '16','nama_kota' => 'KOTA PALEMBANG'),
      array('id' => '1672','provinsi_id' => '16','nama_kota' => 'KOTA PAGAR ALAM'),
      array('id' => '1673','provinsi_id' => '16','nama_kota' => 'KOTA LUBUK LINGGAU'),
      array('id' => '1674','provinsi_id' => '16','nama_kota' => 'KOTA PRABUMULIH'),
      array('id' => '1701','provinsi_id' => '17','nama_kota' => 'KAB. BENGKULU SELATAN'),
      array('id' => '1702','provinsi_id' => '17','nama_kota' => 'KAB. REJANG LEBONG'),
      array('id' => '1703','provinsi_id' => '17','nama_kota' => 'KAB. BENGKULU UTARA'),
      array('id' => '1704','provinsi_id' => '17','nama_kota' => 'KAB. KAUR'),
      array('id' => '1705','provinsi_id' => '17','nama_kota' => 'KAB. SELUMA'),
      array('id' => '1706','provinsi_id' => '17','nama_kota' => 'KAB. MUKO MUKO'),
      array('id' => '1707','provinsi_id' => '17','nama_kota' => 'KAB. LEBONG'),
      array('id' => '1708','provinsi_id' => '17','nama_kota' => 'KAB. KEPAHIANG'),
      array('id' => '1709','provinsi_id' => '17','nama_kota' => 'KAB. BENGKULU TENGAH'),
      array('id' => '1771','provinsi_id' => '17','nama_kota' => 'KOTA BENGKULU'),
      array('id' => '1801','provinsi_id' => '18','nama_kota' => 'KAB. LAMPUNG SELATAN'),
      array('id' => '1802','provinsi_id' => '18','nama_kota' => 'KAB. LAMPUNG TENGAH'),
      array('id' => '1803','provinsi_id' => '18','nama_kota' => 'KAB. LAMPUNG UTARA'),
      array('id' => '1804','provinsi_id' => '18','nama_kota' => 'KAB. LAMPUNG BARAT'),
      array('id' => '1805','provinsi_id' => '18','nama_kota' => 'KAB. TULANG BAWANG'),
      array('id' => '1806','provinsi_id' => '18','nama_kota' => 'KAB. TANGGAMUS'),
      array('id' => '1807','provinsi_id' => '18','nama_kota' => 'KAB. LAMPUNG TIMUR'),
      array('id' => '1808','provinsi_id' => '18','nama_kota' => 'KAB. WAY KANAN'),
      array('id' => '1809','provinsi_id' => '18','nama_kota' => 'KAB. PESAWARAN'),
      array('id' => '1810','provinsi_id' => '18','nama_kota' => 'KAB. PRINGSEWU'),
      array('id' => '1811','provinsi_id' => '18','nama_kota' => 'KAB. MESUJI'),
      array('id' => '1812','provinsi_id' => '18','nama_kota' => 'KAB. TULANG BAWANG BARAT'),
      array('id' => '1813','provinsi_id' => '18','nama_kota' => 'KAB. PESISIR BARAT'),
      array('id' => '1871','provinsi_id' => '18','nama_kota' => 'KOTA BANDAR LAMPUNG'),
      array('id' => '1872','provinsi_id' => '18','nama_kota' => 'KOTA METRO'),
      array('id' => '1901','provinsi_id' => '19','nama_kota' => 'KAB. BANGKA'),
      array('id' => '1902','provinsi_id' => '19','nama_kota' => 'KAB. BELITUNG'),
      array('id' => '1903','provinsi_id' => '19','nama_kota' => 'KAB. BANGKA SELATAN'),
      array('id' => '1904','provinsi_id' => '19','nama_kota' => 'KAB. BANGKA TENGAH'),
      array('id' => '1905','provinsi_id' => '19','nama_kota' => 'KAB. BANGKA BARAT'),
      array('id' => '1906','provinsi_id' => '19','nama_kota' => 'KAB. BELITUNG TIMUR'),
      array('id' => '1971','provinsi_id' => '19','nama_kota' => 'KOTA PANGKAL PINANG'),
      array('id' => '2101','provinsi_id' => '21','nama_kota' => 'KAB. BINTAN'),
      array('id' => '2102','provinsi_id' => '21','nama_kota' => 'KAB. KARIMUN'),
      array('id' => '2103','provinsi_id' => '21','nama_kota' => 'KAB. NATUNA'),
      array('id' => '2104','provinsi_id' => '21','nama_kota' => 'KAB. LINGGA'),
      array('id' => '2105','provinsi_id' => '21','nama_kota' => 'KAB. KEPULAUAN ANAMBAS'),
      array('id' => '2171','provinsi_id' => '21','nama_kota' => 'KOTA BATAM'),
      array('id' => '2172','provinsi_id' => '21','nama_kota' => 'KOTA TANJUNG PINANG'),
      array('id' => '3101','provinsi_id' => '31','nama_kota' => 'KAB. ADM. KEP. SERIBU'),
      array('id' => '3171','provinsi_id' => '31','nama_kota' => 'KOTA ADM. JAKARTA PUSAT'),
      array('id' => '3172','provinsi_id' => '31','nama_kota' => 'KOTA ADM. JAKARTA UTARA'),
      array('id' => '3173','provinsi_id' => '31','nama_kota' => 'KOTA ADM. JAKARTA BARAT'),
      array('id' => '3174','provinsi_id' => '31','nama_kota' => 'KOTA ADM. JAKARTA SELATAN'),
      array('id' => '3175','provinsi_id' => '31','nama_kota' => 'KOTA ADM. JAKARTA TIMUR'),
      array('id' => '3201','provinsi_id' => '32','nama_kota' => 'KAB. BOGOR'),
      array('id' => '3202','provinsi_id' => '32','nama_kota' => 'KAB. SUKABUMI'),
      array('id' => '3203','provinsi_id' => '32','nama_kota' => 'KAB. CIANJUR'),
      array('id' => '3204','provinsi_id' => '32','nama_kota' => 'KAB. BANDUNG'),
      array('id' => '3205','provinsi_id' => '32','nama_kota' => 'KAB. GARUT'),
      array('id' => '3206','provinsi_id' => '32','nama_kota' => 'KAB. TASIKMALAYA'),
      array('id' => '3207','provinsi_id' => '32','nama_kota' => 'KAB. CIAMIS'),
      array('id' => '3208','provinsi_id' => '32','nama_kota' => 'KAB. KUNINGAN'),
      array('id' => '3209','provinsi_id' => '32','nama_kota' => 'KAB. CIREBON'),
      array('id' => '3210','provinsi_id' => '32','nama_kota' => 'KAB. MAJALENGKA'),
      array('id' => '3211','provinsi_id' => '32','nama_kota' => 'KAB. SUMEDANG'),
      array('id' => '3212','provinsi_id' => '32','nama_kota' => 'KAB. INDRAMAYU'),
      array('id' => '3213','provinsi_id' => '32','nama_kota' => 'KAB. SUBANG'),
      array('id' => '3214','provinsi_id' => '32','nama_kota' => 'KAB. PURWAKARTA'),
      array('id' => '3215','provinsi_id' => '32','nama_kota' => 'KAB. KARAWANG'),
      array('id' => '3216','provinsi_id' => '32','nama_kota' => 'KAB. BEKASI'),
      array('id' => '3217','provinsi_id' => '32','nama_kota' => 'KAB. BANDUNG BARAT'),
      array('id' => '3218','provinsi_id' => '32','nama_kota' => 'KAB. PANGANDARAN'),
      array('id' => '3271','provinsi_id' => '32','nama_kota' => 'KOTA BOGOR'),
      array('id' => '3272','provinsi_id' => '32','nama_kota' => 'KOTA SUKABUMI'),
      array('id' => '3273','provinsi_id' => '32','nama_kota' => 'KOTA BANDUNG'),
      array('id' => '3274','provinsi_id' => '32','nama_kota' => 'KOTA CIREBON'),
      array('id' => '3275','provinsi_id' => '32','nama_kota' => 'KOTA BEKASI'),
      array('id' => '3276','provinsi_id' => '32','nama_kota' => 'KOTA DEPOK'),
      array('id' => '3277','provinsi_id' => '32','nama_kota' => 'KOTA CIMAHI'),
      array('id' => '3278','provinsi_id' => '32','nama_kota' => 'KOTA TASIKMALAYA'),
      array('id' => '3279','provinsi_id' => '32','nama_kota' => 'KOTA BANJAR'),
      array('id' => '3301','provinsi_id' => '33','nama_kota' => 'KAB. CILACAP'),
      array('id' => '3302','provinsi_id' => '33','nama_kota' => 'KAB. BANYUMAS'),
      array('id' => '3303','provinsi_id' => '33','nama_kota' => 'KAB. PURBALINGGA'),
      array('id' => '3304','provinsi_id' => '33','nama_kota' => 'KAB. BANJARNEGARA'),
      array('id' => '3305','provinsi_id' => '33','nama_kota' => 'KAB. KEBUMEN'),
      array('id' => '3306','provinsi_id' => '33','nama_kota' => 'KAB. PURWOREJO'),
      array('id' => '3307','provinsi_id' => '33','nama_kota' => 'KAB. WONOSOBO'),
      array('id' => '3308','provinsi_id' => '33','nama_kota' => 'KAB. MAGELANG'),
      array('id' => '3309','provinsi_id' => '33','nama_kota' => 'KAB. BOYOLALI'),
      array('id' => '3310','provinsi_id' => '33','nama_kota' => 'KAB. KLATEN'),
      array('id' => '3311','provinsi_id' => '33','nama_kota' => 'KAB. SUKOHARJO'),
      array('id' => '3312','provinsi_id' => '33','nama_kota' => 'KAB. WONOGIRI'),
      array('id' => '3313','provinsi_id' => '33','nama_kota' => 'KAB. KARANGANYAR'),
      array('id' => '3314','provinsi_id' => '33','nama_kota' => 'KAB. SRAGEN'),
      array('id' => '3315','provinsi_id' => '33','nama_kota' => 'KAB. GROBOGAN'),
      array('id' => '3316','provinsi_id' => '33','nama_kota' => 'KAB. BLORA'),
      array('id' => '3317','provinsi_id' => '33','nama_kota' => 'KAB. REMBANG'),
      array('id' => '3318','provinsi_id' => '33','nama_kota' => 'KAB. PATI'),
      array('id' => '3319','provinsi_id' => '33','nama_kota' => 'KAB. KUDUS'),
      array('id' => '3320','provinsi_id' => '33','nama_kota' => 'KAB. JEPARA'),
      array('id' => '3321','provinsi_id' => '33','nama_kota' => 'KAB. DEMAK'),
      array('id' => '3322','provinsi_id' => '33','nama_kota' => 'KAB. SEMARANG'),
      array('id' => '3323','provinsi_id' => '33','nama_kota' => 'KAB. TEMANGGUNG'),
      array('id' => '3324','provinsi_id' => '33','nama_kota' => 'KAB. KENDAL'),
      array('id' => '3325','provinsi_id' => '33','nama_kota' => 'KAB. BATANG'),
      array('id' => '3326','provinsi_id' => '33','nama_kota' => 'KAB. PEKALONGAN'),
      array('id' => '3327','provinsi_id' => '33','nama_kota' => 'KAB. PEMALANG'),
      array('id' => '3328','provinsi_id' => '33','nama_kota' => 'KAB. TEGAL'),
      array('id' => '3329','provinsi_id' => '33','nama_kota' => 'KAB. BREBES'),
      array('id' => '3371','provinsi_id' => '33','nama_kota' => 'KOTA MAGELANG'),
      array('id' => '3372','provinsi_id' => '33','nama_kota' => 'KOTA SURAKARTA'),
      array('id' => '3373','provinsi_id' => '33','nama_kota' => 'KOTA SALATIGA'),
      array('id' => '3374','provinsi_id' => '33','nama_kota' => 'KOTA SEMARANG'),
      array('id' => '3375','provinsi_id' => '33','nama_kota' => 'KOTA PEKALONGAN'),
      array('id' => '3376','provinsi_id' => '33','nama_kota' => 'KOTA TEGAL'),
      array('id' => '3401','provinsi_id' => '34','nama_kota' => 'KAB. KULON PROGO'),
      array('id' => '3402','provinsi_id' => '34','nama_kota' => 'KAB. BANTUL'),
      array('id' => '3403','provinsi_id' => '34','nama_kota' => 'KAB. GUNUNG KIDUL'),
      array('id' => '3404','provinsi_id' => '34','nama_kota' => 'KAB. SLEMAN'),
      array('id' => '3471','provinsi_id' => '34','nama_kota' => 'KOTA YOGYAKARTA'),
      array('id' => '3501','provinsi_id' => '35','nama_kota' => 'KAB. PACITAN'),
      array('id' => '3502','provinsi_id' => '35','nama_kota' => 'KAB. PONOROGO'),
      array('id' => '3503','provinsi_id' => '35','nama_kota' => 'KAB. TRENGGALEK'),
      array('id' => '3504','provinsi_id' => '35','nama_kota' => 'KAB. TULUNGAGUNG'),
      array('id' => '3505','provinsi_id' => '35','nama_kota' => 'KAB. BLITAR'),
      array('id' => '3506','provinsi_id' => '35','nama_kota' => 'KAB. KEDIRI'),
      array('id' => '3507','provinsi_id' => '35','nama_kota' => 'KAB. MALANG'),
      array('id' => '3508','provinsi_id' => '35','nama_kota' => 'KAB. LUMAJANG'),
      array('id' => '3509','provinsi_id' => '35','nama_kota' => 'KAB. JEMBER'),
      array('id' => '3510','provinsi_id' => '35','nama_kota' => 'KAB. BANYUWANGI'),
      array('id' => '3511','provinsi_id' => '35','nama_kota' => 'KAB. BONDOWOSO'),
      array('id' => '3512','provinsi_id' => '35','nama_kota' => 'KAB. SITUBONDO'),
      array('id' => '3513','provinsi_id' => '35','nama_kota' => 'KAB. PROBOLINGGO'),
      array('id' => '3514','provinsi_id' => '35','nama_kota' => 'KAB. PASURUAN'),
      array('id' => '3515','provinsi_id' => '35','nama_kota' => 'KAB. SIDOARJO'),
      array('id' => '3516','provinsi_id' => '35','nama_kota' => 'KAB. MOJOKERTO'),
      array('id' => '3517','provinsi_id' => '35','nama_kota' => 'KAB. JOMBANG'),
      array('id' => '3518','provinsi_id' => '35','nama_kota' => 'KAB. NGANJUK'),
      array('id' => '3519','provinsi_id' => '35','nama_kota' => 'KAB. MADIUN'),
      array('id' => '3520','provinsi_id' => '35','nama_kota' => 'KAB. MAGETAN'),
      array('id' => '3521','provinsi_id' => '35','nama_kota' => 'KAB. NGAWI'),
      array('id' => '3522','provinsi_id' => '35','nama_kota' => 'KAB. BOJONEGORO'),
      array('id' => '3523','provinsi_id' => '35','nama_kota' => 'KAB. TUBAN'),
      array('id' => '3524','provinsi_id' => '35','nama_kota' => 'KAB. LAMONGAN'),
      array('id' => '3525','provinsi_id' => '35','nama_kota' => 'KAB. GRESIK'),
      array('id' => '3526','provinsi_id' => '35','nama_kota' => 'KAB. BANGKALAN'),
      array('id' => '3527','provinsi_id' => '35','nama_kota' => 'KAB. SAMPANG'),
      array('id' => '3528','provinsi_id' => '35','nama_kota' => 'KAB. PAMEKASAN'),
      array('id' => '3529','provinsi_id' => '35','nama_kota' => 'KAB. SUMENEP'),
      array('id' => '3571','provinsi_id' => '35','nama_kota' => 'KOTA KEDIRI'),
      array('id' => '3572','provinsi_id' => '35','nama_kota' => 'KOTA BLITAR'),
      array('id' => '3573','provinsi_id' => '35','nama_kota' => 'KOTA MALANG'),
      array('id' => '3574','provinsi_id' => '35','nama_kota' => 'KOTA PROBOLINGGO'),
      array('id' => '3575','provinsi_id' => '35','nama_kota' => 'KOTA PASURUAN'),
      array('id' => '3576','provinsi_id' => '35','nama_kota' => 'KOTA MOJOKERTO'),
      array('id' => '3577','provinsi_id' => '35','nama_kota' => 'KOTA MADIUN'),
      array('id' => '3578','provinsi_id' => '35','nama_kota' => 'KOTA SURABAYA'),
      array('id' => '3579','provinsi_id' => '35','nama_kota' => 'KOTA BATU'),
      array('id' => '3601','provinsi_id' => '36','nama_kota' => 'KAB. PANDEGLANG'),
      array('id' => '3602','provinsi_id' => '36','nama_kota' => 'KAB. LEBAK'),
      array('id' => '3603','provinsi_id' => '36','nama_kota' => 'KAB. TANGERANG'),
      array('id' => '3604','provinsi_id' => '36','nama_kota' => 'KAB. SERANG'),
      array('id' => '3671','provinsi_id' => '36','nama_kota' => 'KOTA TANGERANG'),
      array('id' => '3672','provinsi_id' => '36','nama_kota' => 'KOTA CILEGON'),
      array('id' => '3673','provinsi_id' => '36','nama_kota' => 'KOTA SERANG'),
      array('id' => '3674','provinsi_id' => '36','nama_kota' => 'KOTA TANGERANG SELATAN'),
      array('id' => '5101','provinsi_id' => '51','nama_kota' => 'KAB. JEMBRANA'),
      array('id' => '5102','provinsi_id' => '51','nama_kota' => 'KAB. TABANAN'),
      array('id' => '5103','provinsi_id' => '51','nama_kota' => 'KAB. BADUNG'),
      array('id' => '5104','provinsi_id' => '51','nama_kota' => 'KAB. GIANYAR'),
      array('id' => '5105','provinsi_id' => '51','nama_kota' => 'KAB. KLUNGKUNG'),
      array('id' => '5106','provinsi_id' => '51','nama_kota' => 'KAB. BANGLI'),
      array('id' => '5107','provinsi_id' => '51','nama_kota' => 'KAB. KARANGASEM'),
      array('id' => '5108','provinsi_id' => '51','nama_kota' => 'KAB. BULELENG'),
      array('id' => '5171','provinsi_id' => '51','nama_kota' => 'KOTA DENPASAR'),
      array('id' => '5201','provinsi_id' => '52','nama_kota' => 'KAB. LOMBOK BARAT'),
      array('id' => '5202','provinsi_id' => '52','nama_kota' => 'KAB. LOMBOK TENGAH'),
      array('id' => '5203','provinsi_id' => '52','nama_kota' => 'KAB. LOMBOK TIMUR'),
      array('id' => '5204','provinsi_id' => '52','nama_kota' => 'KAB. SUMBAWA'),
      array('id' => '5205','provinsi_id' => '52','nama_kota' => 'KAB. DOMPU'),
      array('id' => '5206','provinsi_id' => '52','nama_kota' => 'KAB. BIMA'),
      array('id' => '5207','provinsi_id' => '52','nama_kota' => 'KAB. SUMBAWA BARAT'),
      array('id' => '5208','provinsi_id' => '52','nama_kota' => 'KAB. LOMBOK UTARA'),
      array('id' => '5271','provinsi_id' => '52','nama_kota' => 'KOTA MATARAM'),
      array('id' => '5272','provinsi_id' => '52','nama_kota' => 'KOTA BIMA'),
      array('id' => '5301','provinsi_id' => '53','nama_kota' => 'KAB. KUPANG'),
      array('id' => '5302','provinsi_id' => '53','nama_kota' => 'KAB TIMOR TENGAH SELATAN'),
      array('id' => '5303','provinsi_id' => '53','nama_kota' => 'KAB. TIMOR TENGAH UTARA'),
      array('id' => '5304','provinsi_id' => '53','nama_kota' => 'KAB. BELU'),
      array('id' => '5305','provinsi_id' => '53','nama_kota' => 'KAB. ALOR'),
      array('id' => '5306','provinsi_id' => '53','nama_kota' => 'KAB. FLORES TIMUR'),
      array('id' => '5307','provinsi_id' => '53','nama_kota' => 'KAB. SIKKA'),
      array('id' => '5308','provinsi_id' => '53','nama_kota' => 'KAB. ENDE'),
      array('id' => '5309','provinsi_id' => '53','nama_kota' => 'KAB. NGADA'),
      array('id' => '5310','provinsi_id' => '53','nama_kota' => 'KAB. MANGGARAI'),
      array('id' => '5311','provinsi_id' => '53','nama_kota' => 'KAB. SUMBA TIMUR'),
      array('id' => '5312','provinsi_id' => '53','nama_kota' => 'KAB. SUMBA BARAT'),
      array('id' => '5313','provinsi_id' => '53','nama_kota' => 'KAB. LEMBATA'),
      array('id' => '5314','provinsi_id' => '53','nama_kota' => 'KAB. ROTE NDAO'),
      array('id' => '5315','provinsi_id' => '53','nama_kota' => 'KAB. MANGGARAI BARAT'),
      array('id' => '5316','provinsi_id' => '53','nama_kota' => 'KAB. NAGEKEO'),
      array('id' => '5317','provinsi_id' => '53','nama_kota' => 'KAB. SUMBA TENGAH'),
      array('id' => '5318','provinsi_id' => '53','nama_kota' => 'KAB. SUMBA BARAT DAYA'),
      array('id' => '5319','provinsi_id' => '53','nama_kota' => 'KAB. MANGGARAI TIMUR'),
      array('id' => '5320','provinsi_id' => '53','nama_kota' => 'KAB. SABU RAIJUA'),
      array('id' => '5321','provinsi_id' => '53','nama_kota' => 'KAB. MALAKA'),
      array('id' => '5371','provinsi_id' => '53','nama_kota' => 'KOTA KUPANG'),
      array('id' => '6101','provinsi_id' => '61','nama_kota' => 'KAB. SAMBAS'),
      array('id' => '6102','provinsi_id' => '61','nama_kota' => 'KAB. MEMPAWAH'),
      array('id' => '6103','provinsi_id' => '61','nama_kota' => 'KAB. SANGGAU'),
      array('id' => '6104','provinsi_id' => '61','nama_kota' => 'KAB. KETAPANG'),
      array('id' => '6105','provinsi_id' => '61','nama_kota' => 'KAB. SINTANG'),
      array('id' => '6106','provinsi_id' => '61','nama_kota' => 'KAB. KAPUAS HULU'),
      array('id' => '6107','provinsi_id' => '61','nama_kota' => 'KAB. BENGKAYANG'),
      array('id' => '6108','provinsi_id' => '61','nama_kota' => 'KAB. LANDAK'),
      array('id' => '6109','provinsi_id' => '61','nama_kota' => 'KAB. SEKADAU'),
      array('id' => '6110','provinsi_id' => '61','nama_kota' => 'KAB. MELAWI'),
      array('id' => '6111','provinsi_id' => '61','nama_kota' => 'KAB. KAYONG UTARA'),
      array('id' => '6112','provinsi_id' => '61','nama_kota' => 'KAB. KUBU RAYA'),
      array('id' => '6171','provinsi_id' => '61','nama_kota' => 'KOTA PONTIANAK'),
      array('id' => '6172','provinsi_id' => '61','nama_kota' => 'KOTA SINGKAWANG'),
      array('id' => '6201','provinsi_id' => '62','nama_kota' => 'KAB. KOTAWARINGIN BARAT'),
      array('id' => '6202','provinsi_id' => '62','nama_kota' => 'KAB. KOTAWARINGIN TIMUR'),
      array('id' => '6203','provinsi_id' => '62','nama_kota' => 'KAB. KAPUAS'),
      array('id' => '6204','provinsi_id' => '62','nama_kota' => 'KAB. BARITO SELATAN'),
      array('id' => '6205','provinsi_id' => '62','nama_kota' => 'KAB. BARITO UTARA'),
      array('id' => '6206','provinsi_id' => '62','nama_kota' => 'KAB. KATINGAN'),
      array('id' => '6207','provinsi_id' => '62','nama_kota' => 'KAB. SERUYAN'),
      array('id' => '6208','provinsi_id' => '62','nama_kota' => 'KAB. SUKAMARA'),
      array('id' => '6209','provinsi_id' => '62','nama_kota' => 'KAB. LAMANDAU'),
      array('id' => '6210','provinsi_id' => '62','nama_kota' => 'KAB. GUNUNG MAS'),
      array('id' => '6211','provinsi_id' => '62','nama_kota' => 'KAB. PULANG PISAU'),
      array('id' => '6212','provinsi_id' => '62','nama_kota' => 'KAB. MURUNG RAYA'),
      array('id' => '6213','provinsi_id' => '62','nama_kota' => 'KAB. BARITO TIMUR'),
      array('id' => '6271','provinsi_id' => '62','nama_kota' => 'KOTA PALANGKARAYA'),
      array('id' => '6301','provinsi_id' => '63','nama_kota' => 'KAB. TANAH LAUT'),
      array('id' => '6302','provinsi_id' => '63','nama_kota' => 'KAB. KOTABARU'),
      array('id' => '6303','provinsi_id' => '63','nama_kota' => 'KAB. BANJAR'),
      array('id' => '6304','provinsi_id' => '63','nama_kota' => 'KAB. BARITO KUALA'),
      array('id' => '6305','provinsi_id' => '63','nama_kota' => 'KAB. TAPIN'),
      array('id' => '6306','provinsi_id' => '63','nama_kota' => 'KAB. HULU SUNGAI SELATAN'),
      array('id' => '6307','provinsi_id' => '63','nama_kota' => 'KAB. HULU SUNGAI TENGAH'),
      array('id' => '6308','provinsi_id' => '63','nama_kota' => 'KAB. HULU SUNGAI UTARA'),
      array('id' => '6309','provinsi_id' => '63','nama_kota' => 'KAB. TABALONG'),
      array('id' => '6310','provinsi_id' => '63','nama_kota' => 'KAB. TANAH BUMBU'),
      array('id' => '6311','provinsi_id' => '63','nama_kota' => 'KAB. BALANGAN'),
      array('id' => '6371','provinsi_id' => '63','nama_kota' => 'KOTA BANJARMASIN'),
      array('id' => '6372','provinsi_id' => '63','nama_kota' => 'KOTA BANJARBARU'),
      array('id' => '6401','provinsi_id' => '64','nama_kota' => 'KAB. PASER'),
      array('id' => '6402','provinsi_id' => '64','nama_kota' => 'KAB. KUTAI KARTANEGARA'),
      array('id' => '6403','provinsi_id' => '64','nama_kota' => 'KAB. BERAU'),
      array('id' => '6407','provinsi_id' => '64','nama_kota' => 'KAB. KUTAI BARAT'),
      array('id' => '6408','provinsi_id' => '64','nama_kota' => 'KAB. KUTAI TIMUR'),
      array('id' => '6409','provinsi_id' => '64','nama_kota' => 'KAB. PENAJAM PASER UTARA'),
      array('id' => '6411','provinsi_id' => '64','nama_kota' => 'KAB. MAHAKAM ULU'),
      array('id' => '6471','provinsi_id' => '64','nama_kota' => 'KOTA BALIKPAPAN'),
      array('id' => '6472','provinsi_id' => '64','nama_kota' => 'KOTA SAMARINDA'),
      array('id' => '6474','provinsi_id' => '64','nama_kota' => 'KOTA BONTANG'),
      array('id' => '6501','provinsi_id' => '65','nama_kota' => 'KAB. BULUNGAN'),
      array('id' => '6502','provinsi_id' => '65','nama_kota' => 'KAB. MALINAU'),
      array('id' => '6503','provinsi_id' => '65','nama_kota' => 'KAB. NUNUKAN'),
      array('id' => '6504','provinsi_id' => '65','nama_kota' => 'KAB. TANA TIDUNG'),
      array('id' => '6571','provinsi_id' => '65','nama_kota' => 'KOTA TARAKAN'),
      array('id' => '7101','provinsi_id' => '71','nama_kota' => 'KAB. BOLAANG MONGONDOW'),
      array('id' => '7102','provinsi_id' => '71','nama_kota' => 'KAB. MINAHASA'),
      array('id' => '7103','provinsi_id' => '71','nama_kota' => 'KAB. KEPULAUAN SANGIHE'),
      array('id' => '7104','provinsi_id' => '71','nama_kota' => 'KAB. KEPULAUAN TALAUD'),
      array('id' => '7105','provinsi_id' => '71','nama_kota' => 'KAB. MINAHASA SELATAN'),
      array('id' => '7106','provinsi_id' => '71','nama_kota' => 'KAB. MINAHASA UTARA'),
      array('id' => '7107','provinsi_id' => '71','nama_kota' => 'KAB. MINAHASA TENGGARA'),
      array('id' => '7108','provinsi_id' => '71','nama_kota' => 'KAB. BOLAANG MONGONDOW UTARA'),
      array('id' => '7109','provinsi_id' => '71','nama_kota' => 'KAB. KEP. SIAU TAGULANDANG BIARO'),
      array('id' => '7110','provinsi_id' => '71','nama_kota' => 'KAB. BOLAANG MONGONDOW TIMUR'),
      array('id' => '7111','provinsi_id' => '71','nama_kota' => 'KAB. BOLAANG MONGONDOW SELATAN'),
      array('id' => '7171','provinsi_id' => '71','nama_kota' => 'KOTA MANADO'),
      array('id' => '7172','provinsi_id' => '71','nama_kota' => 'KOTA BITUNG'),
      array('id' => '7173','provinsi_id' => '71','nama_kota' => 'KOTA TOMOHON'),
      array('id' => '7174','provinsi_id' => '71','nama_kota' => 'KOTA KOTAMOBAGU'),
      array('id' => '7201','provinsi_id' => '72','nama_kota' => 'KAB. BANGGAI'),
      array('id' => '7202','provinsi_id' => '72','nama_kota' => 'KAB. POSO'),
      array('id' => '7203','provinsi_id' => '72','nama_kota' => 'KAB. DONGGALA'),
      array('id' => '7204','provinsi_id' => '72','nama_kota' => 'KAB. TOLI TOLI'),
      array('id' => '7205','provinsi_id' => '72','nama_kota' => 'KAB. BUOL'),
      array('id' => '7206','provinsi_id' => '72','nama_kota' => 'KAB. MOROWALI'),
      array('id' => '7207','provinsi_id' => '72','nama_kota' => 'KAB. BANGGAI KEPULAUAN'),
      array('id' => '7208','provinsi_id' => '72','nama_kota' => 'KAB. PARIGI MOUTONG'),
      array('id' => '7209','provinsi_id' => '72','nama_kota' => 'KAB. TOJO UNA UNA'),
      array('id' => '7210','provinsi_id' => '72','nama_kota' => 'KAB. SIGI'),
      array('id' => '7211','provinsi_id' => '72','nama_kota' => 'KAB. BANGGAI LAUT'),
      array('id' => '7212','provinsi_id' => '72','nama_kota' => 'KAB. MOROWALI UTARA'),
      array('id' => '7271','provinsi_id' => '72','nama_kota' => 'KOTA PALU'),
      array('id' => '7301','provinsi_id' => '73','nama_kota' => 'KAB. KEPULAUAN SELAYAR'),
      array('id' => '7302','provinsi_id' => '73','nama_kota' => 'KAB. BULUKUMBA'),
      array('id' => '7303','provinsi_id' => '73','nama_kota' => 'KAB. BANTAENG'),
      array('id' => '7304','provinsi_id' => '73','nama_kota' => 'KAB. JENEPONTO'),
      array('id' => '7305','provinsi_id' => '73','nama_kota' => 'KAB. TAKALAR'),
      array('id' => '7306','provinsi_id' => '73','nama_kota' => 'KAB. GOWA'),
      array('id' => '7307','provinsi_id' => '73','nama_kota' => 'KAB. SINJAI'),
      array('id' => '7308','provinsi_id' => '73','nama_kota' => 'KAB. BONE'),
      array('id' => '7309','provinsi_id' => '73','nama_kota' => 'KAB. MAROS'),
      array('id' => '7310','provinsi_id' => '73','nama_kota' => 'KAB. PANGKAJENE KEPULAUAN'),
      array('id' => '7311','provinsi_id' => '73','nama_kota' => 'KAB. BARRU'),
      array('id' => '7312','provinsi_id' => '73','nama_kota' => 'KAB. SOPPENG'),
      array('id' => '7313','provinsi_id' => '73','nama_kota' => 'KAB. WAJO'),
      array('id' => '7314','provinsi_id' => '73','nama_kota' => 'KAB. SIDENRENG RAPPANG'),
      array('id' => '7315','provinsi_id' => '73','nama_kota' => 'KAB. PINRANG'),
      array('id' => '7316','provinsi_id' => '73','nama_kota' => 'KAB. ENREKANG'),
      array('id' => '7317','provinsi_id' => '73','nama_kota' => 'KAB. LUWU'),
      array('id' => '7318','provinsi_id' => '73','nama_kota' => 'KAB. TANA TORAJA'),
      array('id' => '7322','provinsi_id' => '73','nama_kota' => 'KAB. LUWU UTARA'),
      array('id' => '7324','provinsi_id' => '73','nama_kota' => 'KAB. LUWU TIMUR'),
      array('id' => '7326','provinsi_id' => '73','nama_kota' => 'KAB. TORAJA UTARA'),
      array('id' => '7371','provinsi_id' => '73','nama_kota' => 'KOTA MAKASSAR'),
      array('id' => '7372','provinsi_id' => '73','nama_kota' => 'KOTA PARE PARE'),
      array('id' => '7373','provinsi_id' => '73','nama_kota' => 'KOTA PALOPO'),
      array('id' => '7401','provinsi_id' => '74','nama_kota' => 'KAB. KOLAKA'),
      array('id' => '7402','provinsi_id' => '74','nama_kota' => 'KAB. KONAWE'),
      array('id' => '7403','provinsi_id' => '74','nama_kota' => 'KAB. MUNA'),
      array('id' => '7404','provinsi_id' => '74','nama_kota' => 'KAB. BUTON'),
      array('id' => '7405','provinsi_id' => '74','nama_kota' => 'KAB. KONAWE SELATAN'),
      array('id' => '7406','provinsi_id' => '74','nama_kota' => 'KAB. BOMBANA'),
      array('id' => '7407','provinsi_id' => '74','nama_kota' => 'KAB. WAKATOBI'),
      array('id' => '7408','provinsi_id' => '74','nama_kota' => 'KAB. KOLAKA UTARA'),
      array('id' => '7409','provinsi_id' => '74','nama_kota' => 'KAB. KONAWE UTARA'),
      array('id' => '7410','provinsi_id' => '74','nama_kota' => 'KAB. BUTON UTARA'),
      array('id' => '7411','provinsi_id' => '74','nama_kota' => 'KAB. KOLAKA TIMUR'),
      array('id' => '7412','provinsi_id' => '74','nama_kota' => 'KAB. KONAWE KEPULAUAN'),
      array('id' => '7413','provinsi_id' => '74','nama_kota' => 'KAB. MUNA BARAT'),
      array('id' => '7414','provinsi_id' => '74','nama_kota' => 'KAB. BUTON TENGAH'),
      array('id' => '7415','provinsi_id' => '74','nama_kota' => 'KAB. BUTON SELATAN'),
      array('id' => '7471','provinsi_id' => '74','nama_kota' => 'KOTA KENDARI'),
      array('id' => '7472','provinsi_id' => '74','nama_kota' => 'KOTA BAU BAU'),
      array('id' => '7501','provinsi_id' => '75','nama_kota' => 'KAB. GORONTALO'),
      array('id' => '7502','provinsi_id' => '75','nama_kota' => 'KAB. BOALEMO'),
      array('id' => '7503','provinsi_id' => '75','nama_kota' => 'KAB. BONE BOLANGO'),
      array('id' => '7504','provinsi_id' => '75','nama_kota' => 'KAB. PAHUWATO'),
      array('id' => '7505','provinsi_id' => '75','nama_kota' => 'KAB. GORONTALO UTARA'),
      array('id' => '7571','provinsi_id' => '75','nama_kota' => 'KOTA GORONTALO'),
      array('id' => '7601','provinsi_id' => '76','nama_kota' => 'KAB. MAMUJU UTARA'),
      array('id' => '7602','provinsi_id' => '76','nama_kota' => 'KAB. MAMUJU'),
      array('id' => '7603','provinsi_id' => '76','nama_kota' => 'KAB. MAMASA'),
      array('id' => '7604','provinsi_id' => '76','nama_kota' => 'KAB. POLEWALI MANDAR'),
      array('id' => '7605','provinsi_id' => '76','nama_kota' => 'KAB. MAJENE'),
      array('id' => '7606','provinsi_id' => '76','nama_kota' => 'KAB. MAMUJU TENGAH'),
      array('id' => '8101','provinsi_id' => '81','nama_kota' => 'KAB. MALUKU TENGAH'),
      array('id' => '8102','provinsi_id' => '81','nama_kota' => 'KAB. MALUKU TENGGARA'),
      array('id' => '8103','provinsi_id' => '81','nama_kota' => 'KAB MALUKU TENGGARA BARAT'),
      array('id' => '8104','provinsi_id' => '81','nama_kota' => 'KAB. BURU'),
      array('id' => '8105','provinsi_id' => '81','nama_kota' => 'KAB. SERAM BAGIAN TIMUR'),
      array('id' => '8106','provinsi_id' => '81','nama_kota' => 'KAB. SERAM BAGIAN BARAT'),
      array('id' => '8107','provinsi_id' => '81','nama_kota' => 'KAB. KEPULAUAN ARU'),
      array('id' => '8108','provinsi_id' => '81','nama_kota' => 'KAB. MALUKU BARAT DAYA'),
      array('id' => '8109','provinsi_id' => '81','nama_kota' => 'KAB. BURU SELATAN'),
      array('id' => '8171','provinsi_id' => '81','nama_kota' => 'KOTA AMBON'),
      array('id' => '8172','provinsi_id' => '81','nama_kota' => 'KOTA TUAL'),
      array('id' => '8201','provinsi_id' => '82','nama_kota' => 'KAB. HALMAHERA BARAT'),
      array('id' => '8202','provinsi_id' => '82','nama_kota' => 'KAB. HALMAHERA TENGAH'),
      array('id' => '8203','provinsi_id' => '82','nama_kota' => 'KAB. HALMAHERA UTARA'),
      array('id' => '8204','provinsi_id' => '82','nama_kota' => 'KAB. HALMAHERA SELATAN'),
      array('id' => '8205','provinsi_id' => '82','nama_kota' => 'KAB. KEPULAUAN SULA'),
      array('id' => '8206','provinsi_id' => '82','nama_kota' => 'KAB. HALMAHERA TIMUR'),
      array('id' => '8207','provinsi_id' => '82','nama_kota' => 'KAB. PULAU MOROTAI'),
      array('id' => '8208','provinsi_id' => '82','nama_kota' => 'KAB. PULAU TALIABU'),
      array('id' => '8271','provinsi_id' => '82','nama_kota' => 'KOTA TERNATE'),
      array('id' => '8272','provinsi_id' => '82','nama_kota' => 'KOTA TIDORE KEPULAUAN'),
      array('id' => '9101','provinsi_id' => '91','nama_kota' => 'KAB. MERAUKE'),
      array('id' => '9102','provinsi_id' => '91','nama_kota' => 'KAB. JAYAWIJAYA'),
      array('id' => '9103','provinsi_id' => '91','nama_kota' => 'KAB. JAYAPURA'),
      array('id' => '9104','provinsi_id' => '91','nama_kota' => 'KAB. NABIRE'),
      array('id' => '9105','provinsi_id' => '91','nama_kota' => 'KAB. KEPULAUAN YAPEN'),
      array('id' => '9106','provinsi_id' => '91','nama_kota' => 'KAB. BIAK NUMFOR'),
      array('id' => '9107','provinsi_id' => '91','nama_kota' => 'KAB. PUNCAK JAYA'),
      array('id' => '9108','provinsi_id' => '91','nama_kota' => 'KAB. PANIAI'),
      array('id' => '9109','provinsi_id' => '91','nama_kota' => 'KAB. MIMIKA'),
      array('id' => '9110','provinsi_id' => '91','nama_kota' => 'KAB. SARMI'),
      array('id' => '9111','provinsi_id' => '91','nama_kota' => 'KAB. KEEROM'),
      array('id' => '9112','provinsi_id' => '91','nama_kota' => 'KAB PEGUNUNGAN BINTANG'),
      array('id' => '9113','provinsi_id' => '91','nama_kota' => 'KAB. YAHUKIMO'),
      array('id' => '9114','provinsi_id' => '91','nama_kota' => 'KAB. TOLIKARA'),
      array('id' => '9115','provinsi_id' => '91','nama_kota' => 'KAB. WAROPEN'),
      array('id' => '9116','provinsi_id' => '91','nama_kota' => 'KAB. BOVEN DIGOEL'),
      array('id' => '9117','provinsi_id' => '91','nama_kota' => 'KAB. MAPPI'),
      array('id' => '9118','provinsi_id' => '91','nama_kota' => 'KAB. ASMAT'),
      array('id' => '9119','provinsi_id' => '91','nama_kota' => 'KAB. SUPIORI'),
      array('id' => '9120','provinsi_id' => '91','nama_kota' => 'KAB. MAMBERAMO RAYA'),
      array('id' => '9121','provinsi_id' => '91','nama_kota' => 'KAB. MAMBERAMO TENGAH'),
      array('id' => '9122','provinsi_id' => '91','nama_kota' => 'KAB. YALIMO'),
      array('id' => '9123','provinsi_id' => '91','nama_kota' => 'KAB. LANNY JAYA'),
      array('id' => '9124','provinsi_id' => '91','nama_kota' => 'KAB. NDUGA'),
      array('id' => '9125','provinsi_id' => '91','nama_kota' => 'KAB. PUNCAK'),
      array('id' => '9126','provinsi_id' => '91','nama_kota' => 'KAB. DOGIYAI'),
      array('id' => '9127','provinsi_id' => '91','nama_kota' => 'KAB. INTAN JAYA'),
      array('id' => '9128','provinsi_id' => '91','nama_kota' => 'KAB. DEIYAI'),
      array('id' => '9171','provinsi_id' => '91','nama_kota' => 'KOTA JAYAPURA'),
      array('id' => '9201','provinsi_id' => '92','nama_kota' => 'KAB. SORONG'),
      array('id' => '9202','provinsi_id' => '92','nama_kota' => 'KAB. MANOKWARI'),
      array('id' => '9203','provinsi_id' => '92','nama_kota' => 'KAB. FAK FAK'),
      array('id' => '9204','provinsi_id' => '92','nama_kota' => 'KAB. SORONG SELATAN'),
      array('id' => '9205','provinsi_id' => '92','nama_kota' => 'KAB. RAJA AMPAT'),
      array('id' => '9206','provinsi_id' => '92','nama_kota' => 'KAB. TELUK BINTUNI'),
      array('id' => '9207','provinsi_id' => '92','nama_kota' => 'KAB. TELUK WONDAMA'),
      array('id' => '9208','provinsi_id' => '92','nama_kota' => 'KAB. KAIMANA'),
      array('id' => '9209','provinsi_id' => '92','nama_kota' => 'KAB. TAMBRAUW'),
      array('id' => '9210','provinsi_id' => '92','nama_kota' => 'KAB. MAYBRAT'),
      array('id' => '9211','provinsi_id' => '92','nama_kota' => 'KAB. MANOKWARI SELATAN'),
      array('id' => '9212','provinsi_id' => '92','nama_kota' => 'KAB. PEGUNUNGAN ARFAK'),
      array('id' => '9271','provinsi_id' => '92','nama_kota' => 'KOTA SORONG')
    ];

    DB::table('kotas')->insert($Kota);
  }
}
